Problem 1

In [17]:
def getCharVector(c: str) -> int:
    c_val = ord(c) - ord('a')
    return 1 << c_val

def isUnique(word: str) -> bool:
    _vector = 0
    for c in word:
        c_ord = getCharVector(c)
        if _vector & c_ord > 0:
            return False
        else:
            _vector |= c_ord
    return True

In [45]:
isUnique('abcdea')

False

Problem 2

In [51]:
from collections import defaultdict
def isPermutation(a:str, b:str) -> bool:
    frec = defaultdict(int)
    if len(a) != len(b):
        return False
    for c in a:
        frec[c] += 1
    for c in b:
        frec[c] -= 1
    for k, v in frec.items():
        if v != 0:
            return False
    return True

In [53]:
isPermutation('aacde','cedaa')

True

Problem 3

In [41]:
def URLfy(s : [], end: int) -> [str]:
    j = len(s)-1
    for i in range(end-1, -1, -1):
        if s[i] != ' ':
            s[j] = s[i]
            j -= 1
        else:
            s[j] = '0'
            s[j-1] = '2'
            s[j-2] = '%'
            j -= 3
    return s

In [42]:
result = URLfy(list('Mr John Smith    '), 13)
print(str(result))

['M', 'r', '%', '2', '0', 'J', 'o', 'h', 'n', '%', '2', '0', 'S', 'm', 'i', 't', 'h']


Problem 4

In [61]:
from collections import defaultdict
def isPermutationPalindrome(s: str) -> bool:
    fr = defaultdict(bool)
    for c in s:
        if c != ' ':
            if fr[c]:
                fr[c] = False
            else:
                fr[c] = True
    count_unique = 0
    for k, v in fr.items():
        if v:
            count_unique += 1
    if count_unique > 1:
        return False
    return True

In [64]:
isPermutationPalindrome('tat cat')

False

Problem 5

In [73]:
def oneAway(a :str, b: str) -> bool:
    diff = abs(len(a) - len(b))
    if diff > 1:
        return False
    
    chars = []
    for c in a:
        chars.append(c)
    for c in b:
        if c not in chars:
            chars.append(c)
        else:
            chars.pop(chars.index(c))
    #print(chars)
    if len(chars) + diff > 2:
        return False
    
    return True

In [76]:
x = [('pale','pal'),('pale','pales'),('pale','bale'),('pale','bake'),('abcdefg ','abcdef ')]
for a,b in x:
    print('{} {}'.format(a,b))
    print(oneAway(a, b))

pale pal
True
pale pales
True
pale bale
True
pale bake
False
abcdefg  abcdef 
True


Problem 6 - If string concatenation is a problem, usage a list and writte the list at the end

In [4]:
def compress(s: str) -> str:
    if len(s) == 0:
        return s
    
    compress = ''
    count = 1
    current = s[1]
    
    for c in s[1:]:
        if current != c:
            compress += current + str(count)
            count = 0
            current = c
        count += 1
    
    compress += current + str(count)
    
    if len(compress) >= len(s):
        return s
    
    return compress
    

In [5]:
compress('aabbbcccceeeeff')

'a2b3c4e4f2'

In [44]:
import numpy as np
n = 4
m = np.zeros((n,n))
num = 0
for i in range(0, n):
    for j in range(0, n):
        m[i,j] = int(num)
        num += 1
print(m)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


In [45]:
def rotateAlt(m) -> bool:
    if (len(m) == 0 or len(m) != len(m[0])):
        return false
    
    n = len(m)
    for layer in range(0, n//2):
        last = n - 1 - layer
        for i in range(layer, last):
            off = i - layer
            tmp = m[layer][i]
            m[layer][i] = m[last-off][layer]
            m[last-off][layer] = m[last][last-off]
            m[last][last-off] = m[i][last]
            m[i][last] = tmp
    
    return True
        

In [46]:
print(rotateAlt(m))
print(m)

True
[[12.  8.  4.  0.]
 [13.  9.  5.  1.]
 [14. 10.  6.  2.]
 [15. 11.  7.  3.]]


In [9]:
def rotate(matrix) -> bool:
    if(len(matrix) == 0 or len(matrix) != len(matrix[0])):
        return False
    n = len(matrix)
    
    for l in range(0, n//2):
        first = l
        last =  n - 1 - l
        for i in range(first, last):
            offset = i - first
            top = matrix[first][i]
            matrix[first][i] = matrix[last-offset][first]
            matrix[last-offset][first] = matrix[last][last-offset]
            matrix[last][last-offset] = matrix[i][last]
            matrix[i][last] = top
    
    return True

In [10]:
rotate(m)
print(m)

[[12.  8.  4.  0.]
 [13.  9.  5.  1.]
 [14. 10.  6.  2.]
 [15. 11.  7.  3.]]
